name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GO_VERSION: 1.19

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Go vet
        run: "go vet ./..."
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build main.go

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test and coverage
        uses: joyarzun/go-testcoverage-action@v1
        with:
          use-ginkgo: true
          coverage-threshold: 80
